# Sentiment Analysis of the Representation of Women and Other Marginalized Identities in the Media {#marginalized-identities-media-representation}

#### Keywords {-}

representation, women, race, media, news, sentiment analysis

## The current state of representation and how it affects understandings of news
The way we represent specific identities fundamentally shapes readers’ interpretation of the news and world events. In the past ten years there has been increasing discussion around how underrepresentation affects people’s perceptions of what they and others are capable of (**Milloy**). 

There are three primary ways people are mentioned in stories: people who are the center of the story, people who help ground the story, such as a witness, and people who are experts. It is crucial when analyzing the frequency with which different identities are represented to separate sources into those groups, because the aggregate might mask the nuances of what’s actually happening. For instance, it may be possible that experts are rarely people of color.

Additionally, it is crucial to understand the themes and sentiments correlated with specific groups. Are women featured as often as men, but mostly as wives and housemakers? Are black people represented proportionally to other races, but typically as people suspected of crimes? By understanding not only the frequency which certain groups are mentioned, but also the context, journalists will be better able to see where they can improve and track progress. 

Despite vocal proponents of diversity in media change has been slow, in part because the writers and producers of major companies are primarily of demographics that are well represented in the media. As a result, they do not see the social need or the business value of changing their work. By illustrating the current state of representation through data, decision makers will gain a better awareness of why underrepresentation is a problem and the changes they can make to improve media and journalism. 

## A deeper look into how data science can bolster our understanding of representation in the news media 
Many people have an intuitive sense that certain identities are overrepresented in the media, but it is much harder to to pinpoint how these identities are portrayed in terms of tone and mood.  

In order to ensure buy-in from the newsroom, this project would be most effective as a partnership between a media company and a local university -- perhaps Columbia, which is known for it's journalism and computer science programs, and The New York Times. The partnership with a university separate from the media company is crucial because it would be impossible to maximize the potential impact of this kind of project if the first company that used the product expected exclusive access. Once the initial research and development phase ends, then this analysis and any tools that come out of it should be open source and available to any newsroom that wants to see how they are performing in terms of representation. 

One of the benefits about partnering with a newsroom is that many newsrooms already do some article tagging that can be used as a starting point for this analysis. 

The first step of this project will be to identify mentions of people in each article and use a library like word2vec to determine whether a person mentioned is a subject, witness or expert. Gender is the easiest dimension of diversity because many names are associated with a gender. The remainder of the names could be hand-tagged, scraped from social media profiles or for public figures, one could leverage their wikipedia pages to determine gender as well as other dimensions of identity. These names with associated dimensions of identity should be open sourced along with the rest of the project in order to limit manual work in the future and bring to light mistaken characterizations. Developing a method of automating this process of identifying people and their identities will likely be the most work-intensive portion of the project. 

Once this identification process is completed the next step is to analyze which kinds of articles mention various demographics of people. The aforementioned article tags might come in handy here as a starting point to identify themes or subject matter of the article. Additionally, it is important to do some sentiment analysis. At a bare minimum, I suggest determining whether the mention is negative or positive. Ideally, the sentiment analysis will be more complex and get into ideas like the tone of the article is positive, but the woman is being praised as "motherly" or a "caretaker" and therefore this article does not push beyond stereotypes. The sentiment analysis is vitally important, because in order for this tool to be actionable, for instance, we need to be able to understand the nuance between an article about a black woman who is prosecuting a criminal and an article about a black woman being charged with a crime. The python library TextBlob would be a good place to start analyzing the sentiment of articles. 

The final product of this analysis is a tool that can be used by the newsroom (primarily editors and those on the masthead) to understand how certain demographics are currently being covered and places where the company could improve. What would be most useful to start would be to show the paper's overall representation statistics and allow viewers to drill down into specific desks or periods of time. I imagine the type of high-level summary that would be useful could contain a breakdown showing frequency of representation for various identities and positive, stereotypical positive (women are caretakers or asians are smart), stereotypical negative (people of color are lazy or criminals) and negative. These breakdowns of what is stereotypical or not should be handled by the machine learning steps described earlier, but should have some transparancy into what categories or article characteristics lead something to be categorized as stereotypical in order to empower editors to take action with this information.  

While individual journalists could access the details of each individual article, the main purpose of them having access would be in order to enable journalists to manually input demographic info that was not available through the initial categorization process. If a journalist (or their editor) is particularly concerned about representation in their coverage, they could look at the articles they have published over time and attempt to expand the subjects they cover. 

It is vitally important that everyone who is a part of the newsroom or the business side has access to this information. By enabling transparancy, the newsroom will be under more pressure to act quickly, which is both the company's moral and financial imperative. 

## Sentiment analysis will provide additional transparency for readers and journalists
A more explicit characterization of how marginalized identities are represented in the media will help journalists to share a wider range of perspectives as well as provide readers with a more critical lens through which to interpret news. Many newsrooms recognize that they have a problem, but don't feel they have access to the soltuions they need in the short term. A tool like this is a small step to improving representation in news by increasing transparancy of what is being published. 

There will be pushback from both the business side and the journalism side from this kind of analysis. The business behind media is struggling and must constantly find a balance between “the right thing to do” and what will ultimately bring in revenue for the company. That said, it is fairly well-documented that diversity often leads to better financial outcomes and in the case of the news media, it is vitally important to expand subscribers beyond the market of older white people. By representing diverse identities more extensively and respectfully, readers of those backgrounds will be more interested in consuming that media (**McKinsey**).

Journalists often believe they are already writing objective pieces and are only “reporting on what’s newsworthy”. They may be concerned that observing the coverage of marginalized groups may lead to coverage being based on fulfilling diversity quotas rather than the most important news. The goal of this tool is not to create arbitrary goals for coverage, but instead to provide journalists and editors with more detailed information on patterns of coverage rather than as a decider for whether an individual article is published. This will come easier for some desks than others. Style and culture can easily accomodate a variety of different identities. Since politics in the US trends very white and male, it is more difficult to have even representation, but it is still worth tracking progress and considering where improvements can be made. It will be crucial to have in depth conversations with those involved with the media industry in order to create lasting change. 


