---
title: "W201 Portfolio"
author: "Jill Rosok"
date: "MIDS Spring 2018"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
link-citations: yes
biblio-style: apalike
---

<!-- This won't be displayed but it will initialize your R session. Add any R libraries you need here. -->

```{r init,include=FALSE,echo=FALSE}
library(magrittr)
readLines('https://www.zotero.org/api/users/4667740/items/top?start=0&limit=25&format=bibtex&key=izM2jxajrcTZ6AKwwZC45jOv&v=1') %>%
writeLines('references.bib')
```


# Welcome! {-}
This is a portfolio of ideas I proposed in RDADA Spring 2018. 

### Representing Marginalized People in Media {-}

My first project seeks to identify the state of representation in the media. Mentions of women and people of color are programatically identified in media and then these articles are analyzed to determine the context and tone of these mentions. This can be used as a benchmarking tool for journalists and their editors to identify benchmarks and where to improve. 

### Computer Generated Art to Accompany Poetry {-}

My second project uses natural langauge processing to identify themes in poems and subsequently create visual art from those themes. 


## About the author {-}

I am a Data Analyst at The New York Times. 

*Updated: `r Sys.Date()`*
